var fs=require("fs")
fs.writeFileSync("1.txt","Hello")
console.log("Data written Succesfully") 
const data=fs.readFileSync('1.txt','utf-8')
console.log(data)
fs.appendFileSync('1.txt','\nNew Content Added')
const data1=fs.readFileSync('1.txt','utf-8')
console.log(data1)
fs.renameSync('1.txt','abc.txt')
console.log('file renamed')
fs.unlinkSync('abc.txt')
console.log('file deleted')
// fs.mkdirSync('myfolder')
// console.log('folder created')
fs.copyFileSync('1.txt','b.txt')
